### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nizwafay** [udacity/andfun-kotlin-guess-it#7]
so, when:
- click play button
- rotate
- back
- rotate
- click play button again, it going to crash.
`java.lang.IllegalStateException: no current navigation node`
is it ack-ed?

**Comment by yegarti** [comment]
After some googling I found this [helpful thread](https://stackoverflow.com/a/60148951/3785666).
Which means this is a bug in the old version that is used in this project.
I can confirm this is not happening in the newest version.

**Comment by Zingam** [comment]
Another possible crash is if you don't initialize:
```
_currentTime.value = DONE
```

**Comment by LaszloLajosT** [comment]
Thank you @yegarti and @TheCodingArcher !

Basically, with this implementation update, my app is not crashing anymore when I rotate my phone and press "play" button.
I wouldn't figure this out by myself as I didn't get an error with the old implementation.
I used this solution in "Step.02-Exercise".

**Comment by o-hackee** [comment]
spent half a day figuring it out, decided to report a problem and the proposed change and voila.. it turned out the issue is old and well-known.. just still there
i'm just learning, but it's quite strange, i'd say, having
`    implementation "android.arch.navigation:navigation-fragment-ktx:1.0.0-rc02"
    implementation "android.arch.navigation:navigation-ui-ktx:1.0.0-rc02"`
while
`android.useAndroidX=true`
and with navigation library first introduced in Lesson 3 project with some more recent version
`version_navigation = "2.3.0"`

**Comment by SudKul** [comment]
We have recently [upgraded](https://github.com/udacity/andfun-kotlin-guess-it/commit/006b7482a0bf8e8cb4a3d503c3f15f3fc3b5a143) the `master` branch code with newer AndroidX dependencies.
Hopefully, the app will work fine now. 
However, we recommend using the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
